export const MODALS = {
  REQUEST_CORPORATE_MANAGEMENT: {
    PARAM_NAME: 'request-corporate',
    CHILDREN: {
      APPROVE: 'approve',
      REJECT: 'reject',
      VIEW: 'view',
    },
  },
  REQUEST_VENDOR_MANAGEMENT: {
    ROOT: 'request-vendor-management-modal',
    PARAM_NAME: 'request-vendor-management-modal',
    VIEW: 'view-request-vendor',
    EDIT: 'edit-request-vendor',
    DEACTIVATE: 'deactivate-request-vendor',
    ACTIVATE: 'activate-request-vendor',
  },
  ADMIN_MANAGEMENT: {
    ROOT: 'admin-management-modal',
    VIEW: 'view-admin',
    EDIT: 'edit-admin',
    DEACTIVATE: 'deactivate-admin',
    ACTIVATE: 'activate-admin',
    FREEZE: 'freeze-wallet',
    UNFREEZE: 'unfreeze-wallet',
    DELETE: 'delete-admin',
  },
  CORPORATE_MANAGEMENT: {
    PARAM_NAME: 'corporate',
    CHILDREN: {
      VIEW: 'view',
      TRANSACTIONS: 'transactions',
      EDIT: 'edit',
      DEACTIVATE: 'deactivate',
      ACTIVATE: 'activate',
      FREEZE: 'freeze',
      UNFREEZE: 'unfreeze',
      DELETE: 'delete',
      KYC: 'kyc',
      VIEW_KYC_DOCUMENT: 'view-kyc-document',
      VIEW_BUSINESS_INFORMATION: 'view-business-information',
    },
  },
  VENDOR_MANAGEMENT: {
    ROOT: 'vendor-management-modal',
    VIEW: 'view-vendor',
    EDIT: 'edit-vendor',
    DEACTIVATE: 'deactivate-vendor',
    ACTIVATE: 'activate-vendor',
    FREEZE: 'freeze-wallet',
    UNFREEZE: 'unfreeze-wallet',
    DELETE: 'delete-vendor',
  },
  PAYMENT: {
    ROOT: 'payment-modal',
    VIEW: 'view-payment',
  },
  CUSTOMER: {
    ROOT: 'customer-modal',
    VIEW: 'view-customer',
    DEACTIVATE: 'deactivate-customer',
    ACTIVATE: 'activate-customer',
    FREEZE: 'freeze-wallet',
    UNFREEZE: 'unfreeze-wallet',
    DELETE: 'delete-customer',
  },
  ADMIN: {
    ROOT: 'admin-modal',
    PARAM_NAME: 'admin-modal',
    VIEW: 'view-admin',
    EDIT: 'edit-admin',
    CREATE: 'invite-admin',
    BULK_INVITE: 'bulk-invite-admin',
    BULK_INVITE_PREVIEW: 'bulk-invite-admin-preview',
    REMOVE: 'delete-admin',
    TOGGLE_STATUS: 'toggle-admin-status',
    RESEND_INVITE: 'resend-admin-invite',
    RESTORE: 'restore-admin',
    PERMANENTLY_DELETE: 'permanently-delete-admin',
  },
};
