export const ROUTES = {
  IN_APP: {
    AUTH: {
      LOGIN: '/',
      REGISTER: '/auth/register',
      RESET_PASSWORD: '/auth/reset-password',
      CREATE_PASSWORD: '/auth/create-password',
      OTP_VERIFICATION: '/auth/otp-verification',
    },
    DASHBOARD: {
      HOME: '/dashboard',
      CUSTOMERS: '/dashboard/customers',
      VENDORS: '/dashboard/vendors',
      CORPORATES: '/dashboard/corporates',
      VENDOR_DETAILS: '/dashboard/vendors/:vendorId',
      CORPORATE_DETAILS: '/dashboard/corporates/:corporateId',
      REQUESTS: {
        VENDOR_REQUESTS: '/dashboard/requests/vendor-requests',
        CORPORATE_REQUESTS: '/dashboard/requests/corporate-requests',
      },
    },
    ADMIN: {
      ROOT: 'admin-modal',
      AUTH: {
        LOGIN: '/admin/auth/login',
        ONBOARD: '/admin/auth/onboard',
        FORGET_PASSWORD: '/admin/auth/forget-password',
        RESET_PASSWORD: '/admin/auth/reset-password',
      },
      HOME: '/admin',
      CUSTOMERS: '/admin/customers',
      VENDORS: '/admin/vendors',
      CORPORATES: '/admin/corporates',
      ADMINS: '/admin/admins',
      ROLES: '/admin/roles',
      ARCHIVED: '/admin/archived',
      TRANSACTIONS: '/admin/transactions',
      PENDING_LIMITS: '/admin/transactions/pending-limits',
      PROFILE: '/admin/profile',
      SETTINGS: '/admin/settings',
      REQUESTS: {
        VENDOR_REQUESTS: '/admin/requests/vendor-requests',
        CORPORATE_REQUESTS: '/admin/requests/corporate-requests',
      },
    },
  },
  ENDPOINT: {
    ADMIN: {
      ROOT: '/admin',
      ARCHIVED: '/admin/archived',
      ROLES: '/admin/roles',
      PROFILE: '/admin/profile',
      ASSIGN_ROLES: '/admin/roles/admins',
      INVITE: '/admin/invite',
      BULK_INVITE: '/admin/bulk-invite',
      EDIT: '/admin/update/profile',
    },
    CUSTOMER: {
      ROOT: '/admin/customers',
      TRANSACTIONS: '/admin/transactions',
      DAILY_LIMIT: '/admin/transactions/pending-limits',
    },
    AGENT: {
      ROOT: '/admin/customers',
      TRANSACTIONS: '/admin/transactions',
    },
    MERCHANT: {
      ROOT: '/admin/customers',
      TRANSACTIONS: '/admin/transactions',
      DAILY_LIMIT: '/admin/transactions/pending-limits',
    },
  },
  EXTERNAL: {},
};

export const ENVIRONMENT = import.meta.env.VITE_NODE_ENV as string;

const API_URLS: { [key: string]: string } = {
  development: import.meta.env.VITE_DEVELOPMENT_BASE_URL,
  staging: import.meta.env.VITE_STAGING_BASE_URL,
  production: import.meta.env.VITE_PRODUCTION_BASE_URL,
};

export const ENV_VARS = {
  API_BASE_URL: API_URLS[ENVIRONMENT] || API_URLS.development,
};

export const isTesting = ENVIRONMENT === 'test';

export const MODAL_NAMES = {
  RECIPIENT: {
    ROOT: 'recipient-modal',
    ASSIGN: 'assign-recipient',
    BULK_UPLOAD: 'bulk-upload-recipient',
    CREATE: 'create-recipient',
  },
  AUTH: {
    ROOT: 'auth-modal',
    LOGOUT: 'logout',
  },
  ROLE: {
    ROOT: 'role-modal',
    CREATE: 'create-role',
    EDIT: 'edit-role',
    SELECT_PERMISSIONS: 'select-permissions',
    EDIT_PERMISSIONS: 'edit-permissions',
    ASSIGN_USER: 'assign-user',
    REASSIGN_ADMINS: 'reassign-admins',
    DELETE: 'delete-role',
    TOGGLE: 'toggle-role',
    REASSIGN_ADMINS_PROMPT: 'reassign-admins-prompt',
  },
  ADMIN: {
    ROOT: 'admin-modal',
    EDIT_ADMIN_ROLE: 'edit-admin-role',
    VIEW: 'view-admin',
    CREATE: 'invite-admin',
    BULK_INVITE: 'bulk-invite-admin',
    BULK_INVITE_PREVIEW: 'bulk-invite-admin-preview',
    EDIT: 'edit-admin',
    REMOVE: 'delete-admin',
    TOGGLE_STATUS: 'toggle-admin-status',
    RESEND_INVITE: 'resend-admin-invite',
    RESTORE: 'restore-admin',
    PERMANENTLY_DELETE: 'permanently-delete-admin',
  },
  CUSTOMER: {
    ROOT: 'customer-modal',
    VIEW: 'view-customer',
    DEACTIVATE: 'deactivate-customer',
    ACTIVATE: 'activate-customer',
    FREEZE: 'freeze-wallet',
    UNFREEZE: 'unfreeze-wallet',
    DELETE: 'delete-customer',
    APPROVE_KYC: 'approve-kyc',
    REJECT_KYC: 'reject-kyc',
    VIEW_KYC: 'view-customer-kyc',
    VIEW_KYC_DOCUMENT: 'view-customer-kyc-document',
    CREATE: 'create-customer',
    UPDATE: 'update-customer-profile',
    VIEW_GUARANTOR: 'view-customer-guarantor',
    TRANSACTIONS: 'customer-transactions',
    APPROVE_DAILY_LIMIT: 'approve-daily-limit',
    REJECT_DAILY_LIMIT: 'reject-daily-limit',
  },
  AGENT: {
    ROOT: 'agent-modal',
    VIEW: 'view-agent',
    DEACTIVATE: 'deactivate-agent',
    ACTIVATE: 'activate-agent',
    FREEZE: 'freeze-wallet',
    UNFREEZE: 'unfreeze-wallet',
    DELETE: 'delete-agent',
    BUSINESS_INFORMATION: 'business-information',
    VIEW_KYC: 'view-agent-kyc',
    VIEW_KYC_DOCUMENT: 'view-agent-kyc-document',
    UPDATE: 'update-agent-profile',
    TRANSACTIONS: 'agent-transactions',
    VIEW_GUARANTOR: 'view-agent-guarantor',
    APPROVE_KYC: 'approve-kyc',
    REJECT_KYC: 'reject-kyc',
  },
  MERCHANT: {
    ROOT: 'merchant-modal',
    VIEW: 'view-merchant',
    DEACTIVATE: 'deactivate-merchant',
    ACTIVATE: 'activate-merchant',
    FREEZE: 'freeze-wallet',
    UNFREEZE: 'unfreeze-wallet',
    DELETE: 'delete-merchant',
    BUSINESS_INFORMATION: 'business-information',
    VIEW_KYC: 'view-merchant-kyc',
    UPDATE: 'update-merchant-profile',
    TRANSACTIONS: 'merchant-transactions',
    VIEW_KYC_DOCUMENT: 'view-kyc-document',
    APPROVE_DAILY_LIMIT: 'approve-daily-limit',
    APPROVE_KYC: 'approve-kyc',
    REJECT_KYC: 'reject-kyc',
    REJECT_DAILY_LIMIT: 'reject-daily-limit',
  },
};

export const DEFAULT_QUERY = {
  page: 1,
  limit: 10,
  search: '',
  status: '',
  date: '',
  role: '',
  type: '',
  tier: '',
  endDate: '',
  startDates: '',
};
